// =============================================================================
// Data Types
// =============================================================================

export interface PmauScore {
  /** Pain score from 1-10 indicating severity of the prospect's problem */
  pain: number
  /** Money score from 1-10 indicating budget capacity */
  money: number
  /** Authority score from 1-10 indicating decision-making power */
  authority: number
  /** Urgency score from 1-10 indicating timeline pressure */
  urgency: number
  /** Total PMAU score (sum of all four metrics) */
  total: number
  /** AI-generated explanation of the PMAU assessment */
  reasoning: string
}

export interface Conversation {
  id: string
  contactId: string
  /** Channel where the conversation originated */
  channel: 'email' | 'chat' | 'form' | 'social-dm' | 'phone'
  /** Current status of the conversation */
  status: 'new' | 'in-progress' | 'qualified' | 'nurture' | 'closed-won' | 'closed-lost' | 'spam'
  /** Subject line or conversation title */
  subject: string
  /** Preview of the first or latest message */
  preview: string
  /** PMAU qualification score generated by AI */
  pmauScore: PmauScore
  /** Where the conversation originated (campaign, page, referral, etc.) */
  source: string
  /** Team member assigned to this conversation (null if unassigned) */
  assignedTo: string | null
  /** ISO timestamp of the most recent message */
  lastMessageAt: string
  /** ISO timestamp when conversation was created */
  createdAt: string
  /** Total number of messages in the thread */
  messageCount: number
  /** Whether there are unread messages */
  isUnread: boolean
  /** Tags for categorization and filtering */
  tags: string[]
}

export interface Contact {
  id: string
  name: string
  email: string
  company: string | null
  title: string | null
  phone: string | null
  /** Lifecycle stage in the customer journey */
  lifecycleStage: 'lead' | 'new-customer' | 'active' | 'dormant' | 'churned'
  /** Total number of conversations with this contact */
  totalConversations: number
  /** ISO timestamp of first contact */
  firstContactedAt: string
  /** ISO timestamp of last activity */
  lastActivityAt: string
}

export interface Message {
  id: string
  conversationId: string
  /** Who sent the message */
  sender: 'contact' | 'ai' | 'team'
  /** Display name of the sender */
  senderName: string
  /** Message content */
  content: string
  /** ISO timestamp when message was sent */
  timestamp: string
  /** Whether the message has been read */
  isRead: boolean
}

export interface Template {
  id: string
  /** Template name for internal reference */
  name: string
  /** Category for organization */
  category: 'qualification' | 'meeting' | 'nurture' | 'follow-up' | 'closing'
  /** Template content with [merge tags] */
  content: string
  /** Number of times this template has been used */
  useCount: number
}

export interface TeamMember {
  id: string
  name: string
  email: string
  role: string
  /** Initials or avatar identifier */
  avatar: string
  /** Current availability status */
  status: 'available' | 'busy' | 'offline'
  /** Area of expertise */
  specialization: string
  /** Current number of assigned conversations */
  activeConversations: number
  /** Average time to respond to messages */
  avgResponseTime: string
}

export interface ChannelAnalytics {
  channel: string
  count: number
  qualificationRate: number
  avgResponseTime: string
}

export interface StatusAnalytics {
  status: string
  count: number
}

export interface Analytics {
  totalConversations: number
  activeConversations: number
  avgResponseTime: string
  /** Percentage of conversations that get qualified */
  qualificationRate: number
  /** Percentage of qualified leads that convert */
  conversionRate: number
  /** Performance breakdown by channel */
  byChannel: ChannelAnalytics[]
  /** Conversation counts by status */
  byStatus: StatusAnalytics[]
}

// =============================================================================
// Component Props
// =============================================================================

export interface ConversationInboxProps {
  /** List of conversations to display */
  conversations: Conversation[]
  /** List of all contacts */
  contacts: Contact[]
  /** Messages for the conversation threads */
  messages: Message[]
  /** Response templates available to use */
  templates: Template[]
  /** Team members who can be assigned conversations */
  teamMembers: TeamMember[]
  /** Analytics data for the dashboard */
  analytics: Analytics
  /** Called when user clicks a conversation to view details */
  onViewConversation?: (conversationId: string) => void
  /** Called when user sends a message in a conversation */
  onSendMessage?: (conversationId: string, content: string, templateId?: string) => void
  /** Called when user manually adjusts PMAU scores */
  onAdjustPmau?: (conversationId: string, pmauScore: PmauScore) => void
  /** Called when user routes a conversation to a team member */
  onRouteToMember?: (conversationId: string, memberId: string) => void
  /** Called when user marks a conversation as qualified */
  onQualify?: (conversationId: string) => void
  /** Called when user marks a conversation as disqualified/nurture */
  onDisqualify?: (conversationId: string) => void
  /** Called when user marks a conversation as spam */
  onMarkAsSpam?: (conversationId: string) => void
  /** Called when user changes conversation status */
  onChangeStatus?: (conversationId: string, status: Conversation['status']) => void
  /** Called when filters are updated */
  onFilterChange?: (filters: ConversationFilters) => void
}

export interface ConversationFilters {
  channels?: string[]
  statuses?: string[]
  pmauMin?: number
  pmauMax?: number
  assignedTo?: string | null
  dateFrom?: string
  dateTo?: string
  searchQuery?: string
}

export interface ConversationDetailProps {
  /** The conversation being viewed */
  conversation: Conversation
  /** The contact associated with this conversation */
  contact: Contact
  /** All messages in the conversation thread */
  messages: Message[]
  /** Response templates available to use */
  templates: Template[]
  /** Team members who can be assigned */
  teamMembers: TeamMember[]
  /** Called when user wants to go back to inbox */
  onBack?: () => void
  /** Called when user sends a message */
  onSendMessage?: (content: string, templateId?: string) => void
  /** Called when user adjusts PMAU scores */
  onAdjustPmau?: (pmauScore: PmauScore) => void
  /** Called when user routes to a team member */
  onRouteToMember?: (memberId: string) => void
  /** Called when user qualifies the lead */
  onQualify?: () => void
  /** Called when user disqualifies the lead */
  onDisqualify?: () => void
  /** Called when user marks as spam */
  onMarkAsSpam?: () => void
}
